belong/urls.py
from django.conf.urls import url,include,patterns
from django.contrib import admin
from . import settings
from taskman import views

urlpatterns = [
    url(r'^taskman/', include('taskman.urls')),
    url(r'^admin/', admin.site.urls),
]


urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

# ex: /taskman/dkalkaejflakhf/sfsfs
   
urlpatterns.append(url(r'', views._404, name='_404'))

taskman/urls.py
from django.conf.urls import url

from . import views

app_name = 'taskman'

urlpatterns = [
    # ex: /taskman/login
    url(r'^login/$', views.login, name='login'),    
    # ex: /taskman/
    url(r'^$', views.index, name='index'),
    # ex: /taskman/feed/
    url(r'^feed/$', views.feed, name='feed'),
    # ex: /taskman/add/   
    url(r'^add/$', views.add, name='add'),
    # ex: /taskman/dkalkaejflakhf/sfsfs
    #url(r'', views._404, name='_404'),    
]

taskman/models.py
from datetime import datetime
from django.shortcuts import get_object_or_404
from django.db import models
from django.db.models.functions import Lower
from django.utils import timezone
from django.contrib.auth.models import User

a = (lambda l: "s<b>" if l > 1 else "<b>")
b = (lambda i: "'," if i > 1 else "")

class TaskManager(models.Manager):

    order_by_list = ['title', 'deadline', 'added_date',         #asc
                     '-title', '-deadline', '-added_date']      #desc
    
    def add_task(self, user, POST):
        if POST['title'] == '':
            raise ValueError
        task = Task(user = user,
                    title = POST['title'],
                    comments = POST['comments'],
                    added_date = timezone.now(),
                    deadline = datetime.strptime(POST['deadline'], '%d %b %Y').strftime('%Y-%m-%d'))
        task.save()

        message = "You created a task <b>'" + task.title + "'</b>, to be completed by " + task.deadline + "."
        Feed.objects.add_feed(user = user, message = message, date = timezone.now())        

    def reopen(self, user, task_keys):
        message = "You reopened task" + a(len(task_keys))
        for index, pkey in enumerate(task_keys,start = 1):
            task = get_object_or_404(Task, pk = pkey)
            task.completed = False
            task.save()
            message += " " + b(index) + "'" + task.title

        message += "'</b>."
        Feed.objects.add_feed(user = user, message = message, date = timezone.now())

    def close(self, user, task_keys):
        message = "You closed task" + a(len(task_keys))
        for index, pkey in enumerate(task_keys,start = 1):
            task = get_object_or_404(Task, pk = pkey)
            task.completed = True
            task.save()
            message += " " + b(index) + "'" + task.title

        message += "'</b>."
        Feed.objects.add_feed(user = user, message = message, date = timezone.now())

    def delete(self, user, task_keys):
        message = "You deleted task" + a(len(task_keys))
        for index, pkey in enumerate(task_keys,start = 1):
            task = get_object_or_404(Task, pk = pkey)
            task.delete()
            message += " " + b(index) + "'" + task.title

        message += "'</b>."
        Feed.objects.add_feed(user = user, message = message, date = timezone.now())

    def edit_all(self, option, user, task_keys):
        if option == "Mark open":
            self.reopen(user = user, task_keys = task_keys)
        elif option == "Mark closed":
            self.close(user = user, task_keys = task_keys)
        elif option == "Delete":
            self.delete(user = user, task_keys = task_keys)

    def get_open_tasks(self, user, order_by = 'deadline'):
        if order_by not in self.order_by_list:
            order_by = 'deadline'

        if order_by.find('title') != -1:
            return user.task_set.filter(completed = False).order_by(Lower(order_by))
        else:
            return user.task_set.filter(completed = False).order_by(order_by)

    def get_closed_tasks(self, user, order_by = 'title'):
        if order_by not in self.order_by_list:
            order_by = 'title'
            
        if order_by.find('title') != -1:
            return user.task_set.filter(completed = True).order_by(Lower(order_by))
        else:
            return user.task_set.filter(completed = True).order_by(order_by)    

class FeedManager(models.Manager):
    def add_feed(self, user, message, date):
        feed = Feed(user = user, message = message, date = timezone.now())
        feed.save()

    
class Task(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 200, blank = False)
    comments = models.TextField(blank = True)
    added_date = models.DateTimeField('Added On', blank = False)
    deadline = models.DateField('Deadline', blank = False)
    completed = models.BooleanField(default = False)
    objects = TaskManager()
    def __str__(self):
        return self.title
        

class Feed(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    message = models.TextField(blank = False)
    date = models.DateTimeField(blank = False)
    objects = FeedManager()
    def __str__(self):
        return self.message    
    

taskman/forms.py
from django import forms
#from django.contrib.admin import widgets
from functools import partial
DateInput = partial(forms.DateInput, {'class': 'datepicker', 'placeholder': '01 Jan 2016'})

        
class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=200)
    password = forms.CharField(label='Password', max_length=200,widget=forms.PasswordInput)


class SignUpForm(forms.Form):
    username = forms.CharField(label='Username*', max_length=200)
    fname = forms.CharField(label='First name', max_length=200, required=False)
    lname = forms.CharField(label='Last name', max_length=200, required=False)
    email = forms.EmailField(label='E-mail*', max_length=200)
    password = forms.CharField(label='Password*', max_length=200,widget=forms.PasswordInput)


class AddTaskFrom(forms.Form):
    title = forms.CharField(label='Title', max_length=200)
    comments = forms.CharField(label='Comments', widget=forms.Textarea, required=False)
    deadline = forms.DateField(label='Deadline',widget=DateInput())

taskman/views.py
from datetime import datetime

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib.auth import authenticate, login as login_auth, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db import IntegrityError 
from .models import Task, Feed
from django.db.models.functions import Lower
from .forms import LoginForm, SignUpForm, AddTaskFrom

# Create your views here.

def login(request):
    if request.method == 'POST':
        if request.POST.get('login', False):
            user = authenticate(username=request.POST['username'], password=request.POST['password'])
            if user is not None:
                login_auth(request, user)
                return HttpResponseRedirect(reverse('taskman:index'))
            else:
                error = "Login failed."
                return render(request, 'taskman/login.html', {'login_error': error, 'loginform' : LoginForm, 'signupform' : SignUpForm})
            
        if request.POST.get('signup', False):
            data = SignUpForm(request.POST)
            try:
                user = User.objects.create_user(username = request.POST['username'],
                                                first_name = request.POST['fname'],
                                                last_name = request.POST['lname'],
                                                email = request.POST['email'],
                                                password = request.POST['password'])                
                user.save()
                user = authenticate(username=request.POST['username'], password=request.POST['password'])
                login_auth(request, user)
                return HttpResponseRedirect(reverse('taskman:index'))
            except IntegrityError:
                error = "Username already taken"
                return render(request, 'taskman/login.html', {'sign_up_error': error, 'loginform' : LoginForm, 'signupform' : SignUpForm})
            except ValueError:
                error = "One of the required fields is blank"
                return render(request, 'taskman/login.html', {'sign_up_error': error, 'loginform' : LoginForm, 'signupform' : SignUpForm})                
  
        if request.POST.get('logout', False):
            logout(request)
        
    return render(request, 'taskman/login.html', {'loginform' : LoginForm, 'signupform' : SignUpForm})


@login_required(redirect_field_name = None, login_url='/taskman/login/')
def index(request):
    user = request.user
    open_order_by = 'deadline'
    closed_order_by = 'title'
    
    if request.method == 'GET':
        type = request.GET.get('type', None)
        if type == 'open':
            open_order_by = request.GET.get('order_by', None)
        elif type == 'closed':
            closed_order_by = request.GET.get('order_by', None)
        
    open_tasks = Task.objects.get_open_tasks(user, open_order_by)
    closed_tasks = Task.objects.get_closed_tasks(user, closed_order_by)
    
    if request.method == 'POST':       
        if 'task_edits' in request.POST:            
            option = request.POST['task_edits']
            task_keys = request.POST.getlist('pk')
            Task.objects.edit_all(option = option, user = user, task_keys = task_keys)          
                
        return HttpResponseRedirect(reverse('taskman:index'))
                
    return render(request, 'taskman/index.html', {'user' : user, 'open_tasks' : open_tasks, 'closed_tasks' :closed_tasks})

    
@login_required(redirect_field_name = None, login_url='/taskman/login/')
def feed(request):
    user = request.user
    feed = user.feed_set.all().order_by('-date') #RF
    context = {'user': user,
               'feed': feed }
    
    return render(request, 'taskman/feed.html', context)


@login_required(redirect_field_name = None, login_url='/taskman/login/')
def add(request):
    user = request.user
    
    if request.method == 'POST':
        try:
            Task.objects.add_task(user, request.POST)
            return HttpResponseRedirect(reverse('taskman:index'))
            
        except ValueError:
            error = 'One of the fields was not properly filled. Try again.'
            return render(request, 'taskman/add.html', {'user' : user, 'addtaskform' : AddTaskFrom, 'add_task_error' :error})
                        
    return render(request, 'taskman/add.html', {'user' : user, 'addtaskform' : AddTaskFrom})


def _404(request):
    return HttpResponseRedirect(reverse('taskman:index'))

taskman/templates/taskman/add.html
{% include "taskman/header.html" %}

<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
<script src="https://code.jquery.com/jquery-1.9.1.js"></script>
<script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

<div class = "add_form">
	<form action="{% url 'taskman:add'%}" method="post">
		{% csrf_token %}
		<table>
		{{ addtaskform.as_table }}
		<th></th>
		<td> 
			<input type="submit" value="Add task" name="add" style="font-size: 20px;"/>
			<font color="red"> {{ add_task_error }} </font>
		<td/>
		</table>	
	</form>
</div>

<script>
	$(document).ready(function() {
		$('.datepicker').datepicker({ dateFormat: 'd M yy' });
	});
</script>

taskman/templates/taskman/feed.html
{% include "taskman/header.html" %}

{% if feed|length_is:"0" %}
	<h3> You don't have any activity.</h3>
{% else %}

	<table class="feed_table">
	{% for f in feed %}
		<tr>
		<td width = "700px">{{ f|safe }}</td>
		<td width = "400px" align = "right">{{ f.date|date:"d M, Y h:i a" }}</td>
		</tr>
	{% endfor %}
	</table>

{% endif %}	

taskman/templates/taskman/header.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'taskman/style.css' %}" />

<div class = "header">
	<h2> Welcome {{ user.username}}, </h2>

	<form action="{% url 'taskman:login'%}" method="post">
		{% csrf_token %}
		<input class = "logout" type="submit" value="Logout" name="logout" style="font-size: 20px;"/>
	</form>
		<a class = "links" href="{% url 'taskman:add'%}" > Add new task </a> 		
		<a class = "links" href="{% url 'taskman:feed'%}" > My activity </a> 
		<a class = "links" href="{% url 'taskman:index'%}" > All tasks </a> 
</div>

taskman/templates/taskman/index.html
{% include "taskman/header.html" %}
<div id="tabs">
	<ul>
		<li><a href="#fragment-1">Open tasks</a></li>
		<li><a href="#fragment-2">Completed tasks</a></li>
	</ul>
	
	<div id="fragment-1">
		<form action="{% url 'taskman:index'%}" method="post">
			{% csrf_token %}
			{% if open_tasks|length_is:"0" %}
				<h3> You don't have any open tasks.</h3>
			{% else %}						
				<input class = "buttons" type="submit" value="Delete" name="task_edits"/>			
				<input class = "buttons" type="submit" value="Mark closed" name="task_edits"/>
				<br>
				<table class = "task_table">	
					<tr bgcolor="#FACC2E">
					  <th width="70px">Select</th>
					  <th width="230px"><a href="?order_by=title&type=open">Title</a></th>
					  <th width="400px">Comments</th>
					  <th width="150px"><a href="?order_by=deadline&type=open">Deadline</a></th>
					  <th width="250px"><a href="?order_by=-added_date&type=open">Added on</a></th>	  
					</tr>
		
					{% for task in open_tasks %}
					<tr bgcolor="{% cycle '#D8D8D8' '#ECECEC'%}">
						<td align="center"><input type="checkbox" value={{task.id}} name="pk"/></td>
						<td>{{ task.title }}</td>
						<td>{{ task.comments }}</td>
						<td>{{ task.deadline|date:"d M, Y" }}</td>
						<td>{{ task.added_date|date:"d M, Y h:i a" }}</td>
					</tr>
					{% endfor %}
				
				</table>
			{% endif %}
		</form>
	</div>
	
	<div id="fragment-2">
		<form action="{% url 'taskman:index'%}" method="post">
			{% csrf_token %}
			{% if closed_tasks|length_is:"0" %}
				<h3> You don't have any closed tasks.</h3>
			{% else %}
				<input class = "buttons" type="submit" value="Delete" name="task_edits"/>
				<input class = "buttons" type="submit" value="Mark open" name="task_edits"/>
				<br>			
				<table class = "task_table">
					<tr bgcolor="#FACC2E">
					  <th width="70px">Select</th>
					  <th width="230px"><a href="?order_by=title&type=closed">Title</a></th>
					  <th width="400px">Comments</th>
					  <th width="150px"><a href="?order_by=-deadline&type=closed">Deadline</a></th>
					  <th width="250px"><a href="?order_by=-added_date&type=closed">Added on</a></th>  
					</tr>
					
					{% for task in closed_tasks %}
					<tr bgcolor="{% cycle '#D8D8D8' '#ECECEC'%}">		
						<td align="center"><input type="checkbox" value={{task.id}} name="pk"/></td>
						<td>{{ task.title }}</td>
						<td>{{ task.comments }}</td>
						<td>{{ task.deadline|date:"d M, Y" }}</td>
						<td>{{ task.added_date|date:"d M, Y h:i a" }}</td>
					</tr>
					{% endfor %}

				</table>
			{% endif %}
		</form>
	</div>
	
</div>

<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
<script src="https://code.jquery.com/jquery-1.9.1.js"></script>
<script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

<script>
	$( "#tabs" ).tabs({
	  active: 0
	});
</script>

taskman/templates/taskman/login.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'taskman/style.css' %}" />

<div class = "holder">
	<div class = "login_form" align="right">
		<h2 style="margin: 0px 150px 0px 0px"> Login </h2>
		<form action="{% url 'taskman:login'%}" method="post">
			{% csrf_token %}
			<table>
			{{ loginform.as_table}}
			<th/> 
			<td> 
				<input type="submit" value="login" name="login" style="font-size: 20px;"/>
				<font color="red"> {{ login_error }} </font>
			</td>
			</table>
			
			
		</form>
	</div>
	<div class = "signup_form">
		<h2 style="margin: 0px 0px 0px 150px"> Sign Up </h2>
		<form action="{% url 'taskman:login'%}" method="post">
			{% csrf_token %}
			<table>
			{{ signupform.as_table}}
			<th/> 
			<td>
				<input type="submit" value="Sign up" name="signup" style="font-size: 20px;"/>
				<font color="red"> {{ sign_up_error }} </font>
			</td>
			</table>
		</form>
	</div>
</div>